name: Run Automation Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Run tests
      run: ./gradlew clean test

    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/test-results/test

    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: build/reports/tests/test
