name: Run UI and API Tests +cucumber

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ui_test:
    name: Run UI Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout UI repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run UI Tests
        run: ./gradlew clean test

  api_test:
    name: Run API Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout API repo
        uses: actions/checkout@v3
        with:
          repository: h333rlina/APi-Test-cucumber
          path: api-test
          # Jika repo API private, tambahkan token:
          # token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run API Tests
        working-directory: api-test
        run: ./gradlew clean test
