name: UI Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-ui:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Install Chrome
      run: browser-actions/setup-chrome@v1.7.3
        sudo apt-get update
        sudo apt-get install -y google-chrome-stabl

    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Run tests
      run: ./gradlew clean test
