name: UI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ui-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout UI repo
      uses: actions/checkout@v3

    - name: Setup JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Give execute permission to gradlew
      run: chmod +x ./gradlew

    - name: Build and run UI tests
      run: ./gradlew clean test
